### PR TITLE
fixes Windows build

### PR DESCRIPTION
**Pull request by vinipsmaker**
The fixed error is:

    src\with_read_timeout.rs:40:13: 40:19 error: unresolved import `select::fd_set`. Maybe a missing `extern crate select`? [E0432]
    src\with_read_timeout.rs:40         use select::fd_set;
                                            ^~~~~~
    src\with_read_timeout.rs:40:13: 40:19 help: run `rustc --explain E0432` to see a detailed explanation
    error: aborting due to previous error

Introduced in commit dfd91141a0c864bd939d9e0f9cd2ff578aeea2f8

Hint taken from
https://github.com/maidsafe/rust-utp/commit/c7a7190b53488cc1f132bc55a6686c3990370409#diff-b4aea3e418ccdb71239b96952d9cddb6R81

### CODE REVIEW

**Comment by vinipsmaker** [comment]
Okay, PR is ready for review now

**Comment by meqif** [comment]
Thank you! I opted to fix it in 534eb4 without splitting the `select` module to another file.

**Comment by vinipsmaker** [comment]
Thanks.

Hey @meqif, could you take a look at #10 please? Also, would you be interested in a PR to replace you platform-specific implementation of timeouts with Rust ones?
